directories:
  "app/channels":
    IrresponsibleModule:
      enabled: false
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    DuplicateMethodCall:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
  "app/jobs":
    IrresponsibleModule:
      enabled: false
  "config":
    IrresponsibleModule:
      enabled: false
  "db/migrate":
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    IrresponsibleModule:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false



detectors:
  UtilityFunction:
    exclude:
      - "ApplicationController#skip_bullet"
      - "ApiHelpers#objects_ids_unsorted"
exclude_paths:
 - node_modules/