# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    services:
     postgres:
      image: postgres:11.5
      ports:
          - 5432:5432
      env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7.1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7

    - name: Install PostgreSQL 11 client
      run: sudo apt-get -yqq install libpq-dev
    - name: Cache Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gem-
    - name: Install Bundler
        run: |
          gem install bundler
    - name: Build App
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Rspec tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        bin/rails db:setup
        bundle exec rspec
    - name: Check security with Brakeman
      run: brakeman
    - name: Rubocop
      run: rubocop
    - name: Code smell detect with reek
      run: reek *